# The image your desired dotnet SDK image
image: mcr.microsoft.com/dotnet/sdk:7.0
# But we attach the docker-in-docker services so we can use it to start containers.
services:
  - docker:dind

variables:
  # Specify the DOCKER_HOST to TestContainers can use the remote docker
  DOCKER_HOST: tcp://docker:2375
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  stage: test
  script:
    - 'dotnet test --no-restore'

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production